name: Main Workflow

on: [push, workflow_dispatch]

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                # * test on different operative systems
                # * test minimal versions: python 3.8.0 + lowest full requirements (of direct packages only)
                # * test latest versions: python 3.x + latest full requirements
                environment: [
                  ["windows-2022", "3.8.0", "--resolution lowest-direct .[full]"],
                  ["windows-2022", "3.x", ".[full]"],
                  ["macos-13", "3.8.0", "--resolution lowest-direct .[full]"],
                  ["macos-13", "3.x", ".[full]"],
                  ["ubuntu-24.04", "3.8.12", "--resolution lowest-direct .[full]"],
                  ["ubuntu-24.04", "3.x", ".[full]"]
                ]
        runs-on: ${{ matrix.environment[0] }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.environment[1] }}
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip pytest uv
                uv pip install --upgrade ${{ matrix.environment[2] }} --system
            - name: Print Versions
              run: |
                python --version
                pip freeze
            - name: Run Tests
              run: pytest -rfP